const PLANS_DATA = [
  {
    "slug": "aetna-medicare-advantra-hmo-pos-h8649-003",
    "name": "Aetna Medicare Advantra (HMO-POS)",
    "carrier": "Aetna Medicare",
    "plan_type": "Medicare Advantage HMO-POS",
    "cms_plan_type": "HMO/HMOPOS",
    "contract_id": "H8649",
    "plan_id": "3",
    "snp": false,
    "premium": 0.0,
    "part_c_premium": 0.0,
    "part_d_premium": 0.0,
    "moop": 3800.0,
    "part_d_deductible": 590.0,
    "primary_care_copay": "",
    "specialist_copay": "$20 copay",
    "er_copay": "$45 copay",
    "urgent_care_copay": "$140 copay",
    "telehealth_copay": "",
    "dme_coinsurance": "0% coinsurance",
    "dental_annual_max": 1250.0,
    "hearing_aid_allowance": null,
    "fitness_program": "SilverSneakers",
    "transportation_trips": "",
    "otc_frequency": "Quarterly",
    "offers_part_d": true,
    "overall_stars": 4,
    "part_c_stars": 4,
    "part_d_stars": 4,
    "summary_of_benefits_url": "",
    "evidence_of_coverage_url": "",
    "counties": [],
    "logo_url": "https://papiofficial.github.io/rsa/logos/aetna.png"
  },
  {
    "slug": "aetna-medicare-advantra-select-hmo-pos-h8649-008",
    "name": "Aetna Medicare Advantra Select (HMO-POS)",
    "carrier": "Aetna Medicare",
    "plan_type": "Medicare Advantage HMO-POS",
    "cms_plan_type": "HMO/HMOPOS",
    "contract_id": "H8649",
    "plan_id": "8",
    "snp": false,
    "premium": 22.0,
    "part_c_premium": 0.0,
    "part_d_premium": 22.0,
    "moop": 6750.0,
    "part_d_deductible": 590.0,
    "primary_care_copay": "",
    "specialist_copay": "$50 copay",
    "er_copay": "$50 copay",
    "urgent_care_copay": "$125 copay",
    "telehealth_copay": "",
    "dme_coinsurance": "0% coinsurance",
    "dental_annual_max": 1250.0,
    "hearing_aid_allowance": null,
    "fitness_program": "SilverSneakers",
    "transportation_trips": "",
    "otc_frequency": "Quarterly",
    "offers_part_d": true,
    "overall_stars": 4,
    "part_c_stars": 4,
    "part_d_stars": 4,
    "summary_of_benefits_url": "",
    "evidence_of_coverage_url": "",
    "counties": [],
    "logo_url": "https://papiofficial.github.io/rsa/logos/aetna.png"
  },
  {
    "slug": "aetna-medicare-choice-ppo-h5521-101",
    "name": "Aetna Medicare Choice (PPO)",
    "carrier": "Aetna Medicare",
    "plan_type": "Medicare Advantage PPO",
    "cms_plan_type": "Local PPO",
    "contract_id": "H5521",
    "plan_id": "101",
    "snp": false,
    "premium": 0.0,
    "part_c_premium": 0.0,
    "part_d_premium": 0.0,
    "moop": 4900.0,
    "part_d_deductible": 590.0,
    "primary_care_copay": "",
    "specialist_copay": "$20 copay",
    "er_copay": "$125 copay",
    "urgent_care_copay": "$45 copay",
    "telehealth_copay": "",
    "dme_coinsurance": "",
    "dental_annual_max": 1000.0,
    "hearing_aid_allowance": null,
    "fitness_program": "SilverSneakers",
    "transportation_trips": "",
    "otc_frequency": "Quarterly",
    "offers_part_d": true,
    "overall_stars": 5,
    "part_c_stars": 4,
    "part_d_stars": 5,
    "summary_of_benefits_url": "",
    "evidence_of_coverage_url": "",
    "counties": [],
    "logo_url": "https://papiofficial.github.io/rsa/logos/aetna.png"
  },
  {
    "slug": "aetna-medicare-dual-preferred-hmo-d-snp-h8649-010",
    "name": "Aetna Medicare Dual Preferred (HMO D-SNP)",
    "carrier": "Aetna Medicare",
    "plan_type": "Medicare Advantage HMO",
    "cms_plan_type": "HMO/HMOPOS",
    "contract_id": "H8649",
    "plan_id": "10",
    "snp": true,
    "premium": 0.0,
    "part_c_premium": 0.0,
    "part_d_premium": 39.8,
    "moop": 9350.0,
    "part_d_deductible": 615.0,
    "primary_care_copay": "",
    "specialist_copay": "$0 copay",
    "er_copay": "$0 copay",
    "urgent_care_copay": "$0 copay",
    "telehealth_copay": "",
    "dme_coinsurance": "$0",
    "dental_annual_max": 250.0,
    "hearing_aid_allowance": null,
    "fitness_program": "SilverSneakers",
    "transportation_trips": "",
    "otc_frequency": "Monthly",
    "offers_part_d": true,
    "overall_stars": 4,
    "part_c_stars": 4,
    "part_d_stars": 4,
    "summary_of_benefits_url": "https://s3.amazonaws.com/webflow-prod-assets/698622c974c0ac921982c3e3/69a3a155553aa4aeb8e10209_Summary-of-Benefits.pdf",
    "evidence_of_coverage_url": "https://s3.amazonaws.com/webflow-prod-assets/698622c974c0ac921982c3e3/69a3a156b832e0993df82fb2_Evidence-of-Coverage.pdf",
    "counties": [],
    "logo_url": "https://papiofficial.github.io/rsa/logos/aetna.png"
  },
  {
    "slug": "aetna-medicare-dual-preferred-ppo-d-snp-h5521-398",
    "name": "Aetna Medicare Dual Preferred (PPO D-SNP)",
    "carrier": "Aetna Medicare",
    "plan_type": "Medicare Advantage PPO",
    "cms_plan_type": "Local PPO",
    "contract_id": "H5521",
    "plan_id": "398",
    "snp": true,
    "premium": 0.0,
    "part_c_premium": 0.0,
    "part_d_premium": 39.9,
    "moop": 9350.0,
    "part_d_deductible": 615.0,
    "primary_care_copay": "$0 copay",
    "specialist_copay": "$0 copay",
    "er_copay": "$115 copay",
    "urgent_care_copay": "",
    "telehealth_copay": "",
    "dme_coinsurance": "",
    "dental_annual_max": null,
    "hearing_aid_allowance": null,
    "fitness_program": "",
    "transportation_trips": "",
    "otc_frequency": "",
    "offers_part_d": true,
    "overall_stars": 5,
    "part_c_stars": 4,
    "part_d_stars": 5,
    "summary_of_benefits_url": "https://s3.amazonaws.com/webflow-prod-assets/698622c974c0ac921982c3e3/69a3a149955fb25967e50876_Summary-of-Benefits.pdf",
    "evidence_of_coverage_url": "https://s3.amazonaws.com/webflow-prod-assets/698622c974c0ac921982c3e3/69a3a14a10f2fb0e8f1cdf13_Evidence-of-Coverage.pdf",
    "counties": [],
    "logo_url": "https://papiofficial.github.io/rsa/logos/aetna.png"
  },
  {
    "slug": "aetna-medicare-eagle-ppo-h5521-351",
    "name": "Aetna Medicare Eagle (PPO)",
    "carrier": "Aetna Medicare",
    "plan_type": "Medicare Advantage PPO",
    "cms_plan_type": "Local PPO",
    "contract_id": "H5521",
    "plan_id": "351",
    "snp": false,
    "premium": 0.0,
    "part_c_premium": 0.0,
    "part_d_premium": null,
    "moop": 8950.0,
    "part_d_deductible": 615.0,
    "primary_care_copay": "$0",
    "specialist_copay": "$40 copay",
    "er_copay": "$130 copay",
    "urgent_care_copay": "$40 copay",
    "telehealth_copay": "",
    "dme_coinsurance": "",
    "dental_annual_max": 2500.0,
    "hearing_aid_allowance": null,
    "fitness_program": "SilverSneakers",
    "transportation_trips": "",
    "otc_frequency": "Quarterly",
    "offers_part_d": false,
    "overall_stars": 5,
    "part_c_stars": 4,
    "part_d_stars": 5,
    "summary_of_benefits_url": "https://s3.amazonaws.com/webflow-prod-assets/698622c974c0ac921982c3e3/69a3a144cfd8e4e75ebb5dbe_Summary-of-Benefits.pdf",
    "evidence_of_coverage_url": "https://s3.amazonaws.com/webflow-prod-assets/698622c974c0ac921982c3e3/69a3a145553aa4aeb8e0fd03_Evidence-of-Coverage.pdf",
    "counties": [],
    "logo_url": "https://papiofficial.github.io/rsa/logos/aetna.png"
  },
  {
    "slug": "aetna-medicare-elite-ppo-h5521-246",
    "name": "Aetna Medicare Elite (PPO)",
    "carrier": "Aetna Medicare",
    "plan_type": "Medicare Advantage PPO",
    "cms_plan_type": "Local PPO",
    "contract_id": "H5521",
    "plan_id": "246",
    "snp": false,
    "premium": 0.0,
    "part_c_premium": 0.0,
    "part_d_premium": 0.0,
    "moop": 5500.0,
    "part_d_deductible": 590.0,
    "primary_care_copay": "",
    "specialist_copay": "$40 copay",
    "er_copay": "$130 copay",
    "urgent_care_copay": "$50 copay",
    "telehealth_copay": "",
    "dme_coinsurance": "",
    "dental_annual_max": 1000.0,
    "hearing_aid_allowance": null,
    "fitness_program": "SilverSneakers",
    "transportation_trips": "",
    "otc_frequency": "Quarterly",
    "offers_part_d": true,
    "overall_stars": 5,
    "part_c_stars": 4,
    "part_d_stars": 5,
    "summary_of_benefits_url": "",
    "evidence_of_coverage_url": "",
    "counties": [],
    "logo_url": "https://papiofficial.github.io/rsa/logos/aetna.png"
  },
  {
    "slug": "aetna-medicare-signature-hmo-h8649-013",
    "name": "Aetna Medicare Signature (HMO)",
    "carrier": "Aetna Medicare",
    "plan_type": "Medicare Advantage Prescription Drug PPO",
    "cms_plan_type": "MAPD",
    "contract_id": "H8649",
    "plan_id": "13",
    "snp": false,
    "premium": 0.0,
    "part_c_premium": 0.0,
    "part_d_premium": 0.0,
    "moop": 5000.0,
    "part_d_deductible": 615.0,
    "primary_care_copay": "$0",
    "specialist_copay": "$45 copay",
    "er_copay": "",
    "urgent_care_copay": "$130 copay",
    "telehealth_copay": "",
    "dme_coinsurance": "20% coinsurance",
    "dental_annual_max": 1000.0,
    "hearing_aid_allowance": null,
    "fitness_program": "SilverSneakers",
    "transportation_trips": "Not covered",
    "otc_frequency": "Quarterly",
    "offers_part_d": true,
    "overall_stars": 4,
    "part_c_stars": 4,
    "part_d_stars": 4,
    "summary_of_benefits_url": "https://s3.amazonaws.com/webflow-prod-assets/698622c974c0ac921982c3e3/69a3978bb5de00bd6718ff3c_Summary-of-Benefits.pdf",
    "evidence_of_coverage_url": "https://s3.amazonaws.com/webflow-prod-assets/698622c974c0ac921982c3e3/69a3978d93e9b37ceb2b03f4_Evidence-of-Coverage.pdf",
    "counties": [],
    "logo_url": "https://papiofficial.github.io/rsa/logos/aetna.png"
  },
  {
    "slug": "aetna-medicare-signature-extra-ppo-h5521-654",
    "name": "Aetna Medicare Signature Extra (PPO)",
    "carrier": "Aetna Medicare",
    "plan_type": "Medicare Advantage Prescription Drug PPO",
    "cms_plan_type": "MAPD",
    "contract_id": "H5521",
    "plan_id": "654",
    "snp": false,
    "premium": 0.0,
    "part_c_premium": 0.0,
    "part_d_premium": 0.0,
    "moop": 8950.0,
    "part_d_deductible": 615.0,
    "primary_care_copay": "$0",
    "specialist_copay": "$40 copay",
    "er_copay": "$130 copay",
    "urgent_care_copay": "$45 copay",
    "telehealth_copay": "",
    "dme_coinsurance": "",
    "dental_annual_max": 1000.0,
    "hearing_aid_allowance": null,
    "fitness_program": "SilverSneakers",
    "transportation_trips": "",
    "otc_frequency": "",
    "offers_part_d": true,
    "overall_stars": 5,
    "part_c_stars": 5,
    "part_d_stars": 5,
    "summary_of_benefits_url": "https://s3.amazonaws.com/webflow-prod-assets/698622c974c0ac921982c3e3/69a397833db42179d091a9af_Summary-of-Benefits.pdf",
    "evidence_of_coverage_url": "https://s3.amazonaws.com/webflow-prod-assets/698622c974c0ac921982c3e3/69a3978548e4ba8cfbc86fbe_Evidence-of-Coverage.pdf",
    "counties": [],
    "logo_url": "https://papiofficial.github.io/rsa/logos/aetna.png"
  },
  {
    "slug": "aetna-medicare-value-ppo-h5521-197",
    "name": "Aetna Medicare Value (PPO)",
    "carrier": "Aetna Medicare",
    "plan_type": "Medicare Advantage PPO",
    "cms_plan_type": "Local PPO",
    "contract_id": "H5521",
    "plan_id": "197",
    "snp": false,
    "premium": 51.0,
    "part_c_premium": 0.3,
    "part_d_premium": 50.7,
    "moop": 6900.0,
    "part_d_deductible": 590.0,
    "primary_care_copay": "$0 copay",
    "specialist_copay": "$45 copay",
    "er_copay": "$110 copay",
    "urgent_care_copay": "$45 copay",
    "telehealth_copay": "",
    "dme_coinsurance": "",
    "dental_annual_max": 1000.0,
    "hearing_aid_allowance": null,
    "fitness_program": "SilverSneakers",
    "transportation_trips": "",
    "otc_frequency": "Quarterly",
    "offers_part_d": true,
    "overall_stars": 5,
    "part_c_stars": 4,
    "part_d_stars": 5,
    "summary_of_benefits_url": "",
    "evidence_of_coverage_url": "",
    "counties": [],
    "logo_url": "https://papiofficial.github.io/rsa/logos/aetna.png"
  },
  {
    "slug": "aetna-medicare-value-plus-ppo-h5521-414",
    "name": "Aetna Medicare Value Plus (PPO)",
    "carrier": "Aetna Medicare",
    "plan_type": "Medicare Advantage PPO",
    "cms_plan_type": "Local PPO",
    "contract_id": "H5521",
    "plan_id": "414",
    "snp": false,
    "premium": 37.6,
    "part_c_premium": 0.0,
    "part_d_premium": 38.1,
    "moop": 8950.0,
    "part_d_deductible": 615.0,
    "primary_care_copay": "$0",
    "specialist_copay": "$35 copay",
    "er_copay": "$130 copay",
    "urgent_care_copay": "$45 copay",
    "telehealth_copay": "",
    "dme_coinsurance": "",
    "dental_annual_max": 1000.0,
    "hearing_aid_allowance": null,
    "fitness_program": "SilverSneakers",
    "transportation_trips": "",
    "otc_frequency": "Quarterly",
    "offers_part_d": true,
    "overall_stars": 5,
    "part_c_stars": 4,
    "part_d_stars": 5,
    "summary_of_benefits_url": "https://s3.amazonaws.com/webflow-prod-assets/698622c974c0ac921982c3e3/69a3a14e00cdb42f974ef264_Summary-of-Benefits.pdf",
    "evidence_of_coverage_url": "https://s3.amazonaws.com/webflow-prod-assets/698622c974c0ac921982c3e3/69a3a150f89cdd4977ee1cd3_Evidence-of-Coverage.pdf",
    "counties": [],
    "logo_url": "https://papiofficial.github.io/rsa/logos/aetna.png"
  },
  {
    "slug": "american-health-advantage-of-utah-hmo-i-snp-h4232-001",
    "name": "American Health Advantage of Utah (HMO I-SNP)",
    "carrier": "American Health Advantage of Utah",
    "plan_type": "Medicare Advantage HMO-POS",
    "cms_plan_type": "HMO/HMOPOS",
    "contract_id": "H4232",
    "plan_id": "1",
    "snp": true,
    "premium": 54.7,
    "part_c_premium": 0.0,
    "part_d_premium": 54.7,
    "moop": 9350.0,
    "part_d_deductible": 590.0,
    "primary_care_copay": "",
    "specialist_copay": "",
    "er_copay": "",
    "urgent_care_copay": "",
    "telehealth_copay": "$0 copay",
    "dme_coinsurance": "0% coinsurance",
    "dental_annual_max": null,
    "hearing_aid_allowance": 0.0,
    "fitness_program": "Included (see plan details)",
    "transportation_trips": "Not covered",
    "otc_frequency": "",
    "offers_part_d": true,
    "overall_stars": null,
    "part_c_stars": null,
    "part_d_stars": 4,
    "summary_of_benefits_url": "",
    "evidence_of_coverage_url": "",
    "counties": [],
    "logo_url": "https://papiofficial.github.io/rsa/logos/american-health-advantage.png"
  },
  {
    "slug": "devoted-c-snp-choice-premium-003-ut-ppo-c-snp-h4473-003",
    "name": "DEVOTED C-SNP CHOICE PREMIUM 003 UT (PPO C-SNP)",
    "carrier": "Devoted Health",
    "plan_type": "Medicare Advantage Prescription Drug PPO",
    "cms_plan_type": "MAPD",
    "contract_id": "H4473",
    "plan_id": "3",
    "snp": true,
    "premium": 37.6,
    "part_c_premium": 0.0,
    "part_d_premium": 37.6,
    "moop": 7800.0,
    "part_d_deductible": 615.0,
    "primary_care_copay": "$0",
    "specialist_copay": "$15 copay",
    "er_copay": "$130 copay",
    "urgent_care_copay": "",
    "telehealth_copay": "",
    "dme_coinsurance": "20%",
    "dental_annual_max": 0.0,
    "hearing_aid_allowance": 399.0,
    "fitness_program": "SilverSneakers",
    "transportation_trips": "Not covered",
    "otc_frequency": "",
    "offers_part_d": true,
    "overall_stars": null,
    "part_c_stars": null,
    "part_d_stars": null,
    "summary_of_benefits_url": "https://s3.amazonaws.com/webflow-prod-assets/698622c974c0ac921982c3e3/69a3979f2b0a34565fdc9f2b_Summary-of-Benefits.pdf",
    "evidence_of_coverage_url": "https://s3.amazonaws.com/webflow-prod-assets/698622c974c0ac921982c3e3/69a397a0df7e93f9bf0d6420_Evidence-of-Coverage.pdf",
    "counties": [],
    "logo_url": "https://papiofficial.github.io/rsa/logos/devoted.png"
  },
  {
    "slug": "devoted-choice-001-ut-ppo-h4473-001",
    "name": "DEVOTED CHOICE 001 UT (PPO)",
    "carrier": "Devoted Health",
    "plan_type": "Medicare Advantage Prescription Drug PPO",
    "cms_plan_type": "MAPD",
    "contract_id": "H4473",
    "plan_id": "1",
    "snp": false,
    "premium": 0.0,
    "part_c_premium": 0.0,
    "part_d_premium": 0.0,
    "moop": 7500.0,
    "part_d_deductible": 615.0,
    "primary_care_copay": "$0",
    "specialist_copay": "$20 copay",
    "er_copay": "$130 copay",
    "urgent_care_copay": "",
    "telehealth_copay": "",
    "dme_coinsurance": "20%",
    "dental_annual_max": 0.0,
    "hearing_aid_allowance": 399.0,
    "fitness_program": "SilverSneakers",
    "transportation_trips": "Not covered",
    "otc_frequency": "",
    "offers_part_d": true,
    "overall_stars": null,
    "part_c_stars": null,
    "part_d_stars": null,
    "summary_of_benefits_url": "https://s3.amazonaws.com/webflow-prod-assets/698622c974c0ac921982c3e3/69a3979248e4ba8cfbc8743f_Summary-of-Benefits.pdf",
    "evidence_of_coverage_url": "https://s3.amazonaws.com/webflow-prod-assets/698622c974c0ac921982c3e3/69a3979397eddc436cf4b170_Evidence-of-Coverage.pdf",
    "counties": [],
    "logo_url": "https://papiofficial.github.io/rsa/logos/devoted.png"
  },
  {
    "slug": "devoted-choice-giveback-002-ut-ppo-h4473-002",
    "name": "DEVOTED CHOICE GIVEBACK 002 UT (PPO)",
    "carrier": "Devoted Health",
    "plan_type": "Medicare Advantage Prescription Drug PPO",
    "cms_plan_type": "MAPD",
    "contract_id": "H4473",
    "plan_id": "2",
    "snp": false,
    "premium": 0.0,
    "part_c_premium": 0.0,
    "part_d_premium": 0.0,
    "moop": 13900.0,
    "part_d_deductible": 615.0,
    "primary_care_copay": "$0",
    "specialist_copay": "$55 copay",
    "er_copay": "$115 copay",
    "urgent_care_copay": "",
    "telehealth_copay": "",
    "dme_coinsurance": "15%",
    "dental_annual_max": 0.0,
    "hearing_aid_allowance": 599.0,
    "fitness_program": "SilverSneakers",
    "transportation_trips": "Not covered",
    "otc_frequency": "",
    "offers_part_d": true,
    "overall_stars": null,
    "part_c_stars": null,
    "part_d_stars": null,
    "summary_of_benefits_url": "https://s3.amazonaws.com/webflow-prod-assets/698622c974c0ac921982c3e3/69a39798354b439bb7d7f9bb_Summary-of-Benefits.pdf",
    "evidence_of_coverage_url": "https://s3.amazonaws.com/webflow-prod-assets/698622c974c0ac921982c3e3/69a3979a725736fc7b887a03_Evidence-of-Coverage.pdf",
    "counties": [],
    "logo_url": "https://papiofficial.github.io/rsa/logos/devoted.png"
  },
  {
    "slug": "devoted-dual-choice-full-004-ut-ppo-d-snp-h4473-004",
    "name": "DEVOTED DUAL CHOICE FULL 004 UT (PPO D-SNP)",
    "carrier": "Devoted Health",
    "plan_type": "Medicare Advantage Prescription Drug PPO",
    "cms_plan_type": "MAPD",
    "contract_id": "H4473",
    "plan_id": "4",
    "snp": true,
    "premium": 0.0,
    "part_c_premium": 0.0,
    "part_d_premium": 34.4,
    "moop": 13900.0,
    "part_d_deductible": 615.0,
    "primary_care_copay": "$0",
    "specialist_copay": "$0 copay",
    "er_copay": "$0 copay",
    "urgent_care_copay": "",
    "telehealth_copay": "$0 copay",
    "dme_coinsurance": "$0",
    "dental_annual_max": 9250.0,
    "hearing_aid_allowance": 0.0,
    "fitness_program": "SilverSneakers",
    "transportation_trips": "Not covered",
    "otc_frequency": "",
    "offers_part_d": true,
    "overall_stars": null,
    "part_c_stars": null,
    "part_d_stars": null,
    "summary_of_benefits_url": "https://s3.amazonaws.com/webflow-prod-assets/698622c974c0ac921982c3e3/69a397a4e64f119c11f4f500_Summary-of-Benefits.pdf",
    "evidence_of_coverage_url": "https://s3.amazonaws.com/webflow-prod-assets/698622c974c0ac921982c3e3/69a397a6e64f119c11f4f607_Evidence-of-Coverage.pdf",
    "counties": [],
    "logo_url": "https://papiofficial.github.io/rsa/logos/devoted.png"
  },
  {
    "slug": "cigna-preferred-medicare-hmo-h7389-001",
    "name": "Cigna Preferred Medicare (HMO)",
    "carrier": "HealthSpring",
    "plan_type": "Medicare Advantage HMO",
    "cms_plan_type": "HMO/HMOPOS",
    "contract_id": "H7389",
    "plan_id": "1",
    "snp": false,
    "premium": 0.0,
    "part_c_premium": 0.0,
    "part_d_premium": 0.0,
    "moop": 4200.0,
    "part_d_deductible": 0.0,
    "primary_care_copay": "$0 copay",
    "specialist_copay": "$20 copay",
    "er_copay": "$125 copay",
    "urgent_care_copay": "$25 copay",
    "telehealth_copay": "",
    "dme_coinsurance": "0% coinsurance",
    "dental_annual_max": null,
    "hearing_aid_allowance": 0.0,
    "fitness_program": "Silver&Fit",
    "transportation_trips": "",
    "otc_frequency": "",
    "offers_part_d": true,
    "overall_stars": 3,
    "part_c_stars": 3,
    "part_d_stars": 2,
    "summary_of_benefits_url": "",
    "evidence_of_coverage_url": "",
    "counties": [],
    "logo_url": "https://papiofficial.github.io/rsa/logos/healthspring.png"
  },
  {
    "slug": "cigna-true-choice-courage-medicare-ppo-h7849-138",
    "name": "Cigna True Choice Courage Medicare (PPO)",
    "carrier": "HealthSpring",
    "plan_type": "Medicare Advantage PPO",
    "cms_plan_type": "Local PPO",
    "contract_id": "H7849",
    "plan_id": "138",
    "snp": false,
    "premium": null,
    "part_c_premium": 0.0,
    "part_d_premium": null,
    "moop": 5700.0,
    "part_d_deductible": null,
    "primary_care_copay": "$0 copay",
    "specialist_copay": "$30 copay",
    "er_copay": "$125 copay",
    "urgent_care_copay": "$30 copay",
    "telehealth_copay": "",
    "dme_coinsurance": "0% coinsurance",
    "dental_annual_max": null,
    "hearing_aid_allowance": null,
    "fitness_program": "Silver&Fit",
    "transportation_trips": "",
    "otc_frequency": "",
    "offers_part_d": false,
    "overall_stars": 3,
    "part_c_stars": 3,
    "part_d_stars": 3,
    "summary_of_benefits_url": "",
    "evidence_of_coverage_url": "",
    "counties": [],
    "logo_url": "https://papiofficial.github.io/rsa/logos/healthspring.png"
  },
  {
    "slug": "cigna-true-choice-medicare-ppo-h7849-029",
    "name": "Cigna True Choice Medicare (PPO)",
    "carrier": "HealthSpring",
    "plan_type": "Medicare Advantage PPO",
    "cms_plan_type": "Local PPO",
    "contract_id": "H7849",
    "plan_id": "29",
    "snp": false,
    "premium": 0.0,
    "part_c_premium": 0.0,
    "part_d_premium": 0.0,
    "moop": 4300.0,
    "part_d_deductible": 0.0,
    "primary_care_copay": "$25 copay",
    "specialist_copay": "$30 copay",
    "er_copay": "$125 copay",
    "urgent_care_copay": "$30 copay",
    "telehealth_copay": "",
    "dme_coinsurance": "0% coinsurance",
    "dental_annual_max": null,
    "hearing_aid_allowance": null,
    "fitness_program": "Silver&Fit",
    "transportation_trips": "",
    "otc_frequency": "",
    "offers_part_d": true,
    "overall_stars": 3,
    "part_c_stars": 3,
    "part_d_stars": 3,
    "summary_of_benefits_url": "",
    "evidence_of_coverage_url": "",
    "counties": [],
    "logo_url": "https://papiofficial.github.io/rsa/logos/healthspring.png"
  },
  {
    "slug": "healthspring-premier-hmo-pos-h0439-024",
    "name": "HealthSpring Premier (HMO-POS)",
    "carrier": "HealthSpring",
    "plan_type": "Medicare Advantage Prescription Drug PPO",
    "cms_plan_type": "MAPD",
    "contract_id": "H0439",
    "plan_id": "24",
    "snp": false,
    "premium": 0.0,
    "part_c_premium": 0.0,
    "part_d_premium": 0.0,
    "moop": 3500.0,
    "part_d_deductible": 615.0,
    "primary_care_copay": "$0 copay",
    "specialist_copay": "$10 copay",
    "er_copay": "$140 copay",
    "urgent_care_copay": "$35 copay",
    "telehealth_copay": "",
    "dme_coinsurance": "20% coinsurance",
    "dental_annual_max": 35.0,
    "hearing_aid_allowance": 0.0,
    "fitness_program": "",
    "transportation_trips": "",
    "otc_frequency": "",
    "offers_part_d": true,
    "overall_stars": 4,
    "part_c_stars": 4,
    "part_d_stars": 4,
    "summary_of_benefits_url": "https://s3.amazonaws.com/webflow-prod-assets/698622c974c0ac921982c3e3/69a397abb5de00bd671907e5_Summary-of-Benefits.pdf",
    "evidence_of_coverage_url": "https://s3.amazonaws.com/webflow-prod-assets/698622c974c0ac921982c3e3/69a397acf89cdd4977eb4624_Evidence-of-Coverage.pdf",
    "counties": [],
    "logo_url": "https://papiofficial.github.io/rsa/logos/healthspring.png"
  },
  {
    "slug": "humana-dual-select-h7617-039-ppo-d-snp",
    "name": "Humana Dual Select H7617-039 (PPO D-SNP)",
    "carrier": "Humana",
    "plan_type": "Medicare Advantage Prescription Drug PPO",
    "cms_plan_type": "MAPD",
    "contract_id": "H7617",
    "plan_id": "39",
    "snp": true,
    "premium": 27.9,
    "part_c_premium": 0.0,
    "part_d_premium": 27.9,
    "moop": 13900.0,
    "part_d_deductible": 615.0,
    "primary_care_copay": "$0",
    "specialist_copay": "$30 copay",
    "er_copay": "$115 copay",
    "urgent_care_copay": "$40 copay",
    "telehealth_copay": "$0 copay",
    "dme_coinsurance": "$0",
    "dental_annual_max": 0.0,
    "hearing_aid_allowance": 0.0,
    "fitness_program": "SilverSneakers",
    "transportation_trips": "Not covered",
    "otc_frequency": "",
    "offers_part_d": true,
    "overall_stars": 5,
    "part_c_stars": 5,
    "part_d_stars": 4,
    "summary_of_benefits_url": "https://s3.amazonaws.com/webflow-prod-assets/698622c974c0ac921982c3e3/69a397e200cdb42f974d3ba5_Summary-of-Benefits.pdf",
    "evidence_of_coverage_url": "https://s3.amazonaws.com/webflow-prod-assets/698622c974c0ac921982c3e3/69a397e465b155137ff22a13_Evidence-of-Coverage.pdf",
    "counties": [],
    "logo_url": "https://papiofficial.github.io/rsa/logos/humana.png"
  },
  {
    "slug": "humana-full-access-h7617-025-ppo",
    "name": "Humana Full Access H7617-025 (PPO)",
    "carrier": "Humana",
    "plan_type": "Medicare Advantage Prescription Drug PPO",
    "cms_plan_type": "MAPD",
    "contract_id": "H7617",
    "plan_id": "25",
    "snp": false,
    "premium": 29.0,
    "part_c_premium": 0.0,
    "part_d_premium": 29.0,
    "moop": 5500.0,
    "part_d_deductible": 615.0,
    "primary_care_copay": "$0",
    "specialist_copay": "$10 copay",
    "er_copay": "",
    "urgent_care_copay": "$50 copay",
    "telehealth_copay": "$0 copay",
    "dme_coinsurance": "$0",
    "dental_annual_max": 75.0,
    "hearing_aid_allowance": "$999",
    "fitness_program": "SilverSneakers",
    "transportation_trips": "",
    "otc_frequency": "",
    "offers_part_d": true,
    "overall_stars": 5,
    "part_c_stars": 5,
    "part_d_stars": 4,
    "summary_of_benefits_url": "https://s3.amazonaws.com/webflow-prod-assets/698622c974c0ac921982c3e3/69a397cbc4ee1d555d99c2f4_Summary-of-Benefits.pdf",
    "evidence_of_coverage_url": "https://s3.amazonaws.com/webflow-prod-assets/698622c974c0ac921982c3e3/69a397ce9e88f17011fcb881_Evidence-of-Coverage.pdf",
    "counties": [],
    "logo_url": "https://papiofficial.github.io/rsa/logos/humana.png",
    "vision_allowance": "$150"
  },
  {
    "slug": "humana-gold-plus-h2486-003-hmo",
    "name": "Humana Gold Plus H2486-003 (HMO)",
    "carrier": "Humana",
    "plan_type": "Medicare Advantage HMO",
    "cms_plan_type": "HMO/HMOPOS",
    "contract_id": "H2486",
    "plan_id": "3",
    "snp": false,
    "premium": 0.0,
    "part_c_premium": 0.0,
    "part_d_premium": 0.0,
    "moop": 5000.0,
    "part_d_deductible": 615.0,
    "primary_care_copay": "$0 copay",
    "specialist_copay": "$20 copay",
    "er_copay": "$115 copay",
    "urgent_care_copay": "$50 copay",
    "telehealth_copay": "$0 copay",
    "dme_coinsurance": "$0",
    "dental_annual_max": 1000.0,
    "hearing_aid_allowance": "$999",
    "fitness_program": "SilverSneakers",
    "transportation_trips": "",
    "otc_frequency": "",
    "offers_part_d": true,
    "overall_stars": 3,
    "part_c_stars": 4,
    "part_d_stars": 4,
    "summary_of_benefits_url": "https://s3.amazonaws.com/webflow-prod-assets/698622c974c0ac921982c3e3/69a3a16a91c29a96f75ca444_Summary-of-Benefits.pdf",
    "evidence_of_coverage_url": "https://s3.amazonaws.com/webflow-prod-assets/698622c974c0ac921982c3e3/69a3a16c05866d678ee6c991_Evidence-of-Coverage.pdf",
    "counties": [],
    "logo_url": "https://papiofficial.github.io/rsa/logos/humana.png",
    "vision_allowance": "$395"
  },
  {
    "slug": "humana-usaa-honor-giveback-ppo-h7617-021",
    "name": "Humana USAA Honor Giveback (PPO)",
    "carrier": "Humana",
    "plan_type": "Medicare Advantage PPO",
    "cms_plan_type": "MA",
    "contract_id": "H7617",
    "plan_id": "21",
    "snp": false,
    "premium": 0.0,
    "part_c_premium": 0.0,
    "part_d_premium": null,
    "moop": 13900.0,
    "part_d_deductible": 615.0,
    "primary_care_copay": "$0",
    "specialist_copay": "$45 copay",
    "er_copay": "",
    "urgent_care_copay": "$40 copay",
    "telehealth_copay": "$0 copay",
    "dme_coinsurance": "$0",
    "dental_annual_max": 75.0,
    "hearing_aid_allowance": "$999",
    "fitness_program": "SilverSneakers",
    "transportation_trips": "",
    "otc_frequency": "Quarterly",
    "offers_part_d": false,
    "overall_stars": 5,
    "part_c_stars": 5,
    "part_d_stars": 4,
    "summary_of_benefits_url": "https://s3.amazonaws.com/webflow-prod-assets/698622c974c0ac921982c3e3/69a397c300cdb42f974d2eed_Summary-of-Benefits.pdf",
    "evidence_of_coverage_url": "https://s3.amazonaws.com/webflow-prod-assets/698622c974c0ac921982c3e3/69a397c505b730b23c2c9a0c_Evidence-of-Coverage.pdf",
    "counties": [],
    "logo_url": "https://papiofficial.github.io/rsa/logos/humana.png",
    "otc_credit": "$50"
  },
  {
    "slug": "humana-usaa-honor-giveback-ppo-h5216-455",
    "name": "Humana USAA Honor Giveback (PPO)",
    "carrier": "Humana",
    "plan_type": "Medicare Advantage PPO",
    "cms_plan_type": "MA",
    "contract_id": "H5216",
    "plan_id": "455",
    "snp": false,
    "premium": 0.0,
    "part_c_premium": 0.0,
    "part_d_premium": null,
    "moop": 10100.0,
    "part_d_deductible": 615.0,
    "primary_care_copay": "$0",
    "specialist_copay": "$40 copay",
    "er_copay": "$130 copay",
    "urgent_care_copay": "$50 copay",
    "telehealth_copay": "$0 copay",
    "dme_coinsurance": "$0",
    "dental_annual_max": 75.0,
    "hearing_aid_allowance": "$999",
    "fitness_program": "SilverSneakers",
    "transportation_trips": "",
    "otc_frequency": "Quarterly",
    "offers_part_d": false,
    "overall_stars": 4,
    "part_c_stars": 4,
    "part_d_stars": 3,
    "summary_of_benefits_url": "https://s3.amazonaws.com/webflow-prod-assets/698622c974c0ac921982c3e3/69a397b4b5de00bd67190902_Summary-of-Benefits.pdf",
    "evidence_of_coverage_url": "https://s3.amazonaws.com/webflow-prod-assets/698622c974c0ac921982c3e3/69a397b62b0a34565fdca2f7_Evidence-of-Coverage.pdf",
    "counties": [],
    "logo_url": "https://papiofficial.github.io/rsa/logos/humana.png",
    "otc_credit": "$50",
    "vision_allowance": "$150"
  },
  {
    "slug": "humana-usaa-honor-giveback-ppo-h5216-427",
    "name": "Humana USAA Honor Giveback (PPO)",
    "carrier": "Humana",
    "plan_type": "Medicare Advantage HMO",
    "cms_plan_type": "Local PPO",
    "contract_id": "H5216",
    "plan_id": "427",
    "snp": false,
    "premium": 0.0,
    "part_c_premium": 0.0,
    "part_d_premium": null,
    "moop": 13900.0,
    "part_d_deductible": 615.0,
    "primary_care_copay": "$0",
    "specialist_copay": "$50 copay",
    "er_copay": "$115 copay",
    "urgent_care_copay": "$40 copay",
    "telehealth_copay": "$0 copay",
    "dme_coinsurance": "$0",
    "dental_annual_max": 75.0,
    "hearing_aid_allowance": "$999",
    "fitness_program": "SilverSneakers",
    "transportation_trips": "",
    "otc_frequency": "Quarterly",
    "offers_part_d": false,
    "overall_stars": 4,
    "part_c_stars": 4,
    "part_d_stars": 4,
    "summary_of_benefits_url": "https://s3.amazonaws.com/webflow-prod-assets/698622c974c0ac921982c3e3/69a3a17797eddc436cf757e4_Summary-of-Benefits.pdf",
    "evidence_of_coverage_url": "https://s3.amazonaws.com/webflow-prod-assets/698622c974c0ac921982c3e3/69a3a17910f2fb0e8f1d0458_Evidence-of-Coverage.pdf",
    "counties": [],
    "logo_url": "https://papiofficial.github.io/rsa/logos/humana.png",
    "otc_credit": "$50"
  },
  {
    "slug": "humana-usaa-honor-giveback-ppo-h5216-301",
    "name": "Humana USAA Honor Giveback (PPO)",
    "carrier": "Humana",
    "plan_type": "Medicare Advantage PPO",
    "cms_plan_type": "Local PPO",
    "contract_id": "H5216",
    "plan_id": "301",
    "snp": false,
    "premium": null,
    "part_c_premium": 0.0,
    "part_d_premium": null,
    "moop": 5100.0,
    "part_d_deductible": null,
    "primary_care_copay": "",
    "specialist_copay": "$40 copay",
    "er_copay": "$125 copay",
    "urgent_care_copay": "$55 copay",
    "telehealth_copay": "$0 copay",
    "dme_coinsurance": "",
    "dental_annual_max": null,
    "hearing_aid_allowance": null,
    "fitness_program": "SilverSneakers",
    "transportation_trips": "",
    "otc_frequency": "",
    "offers_part_d": false,
    "overall_stars": 4,
    "part_c_stars": 4,
    "part_d_stars": 4,
    "summary_of_benefits_url": "",
    "evidence_of_coverage_url": "",
    "counties": [],
    "logo_url": "https://papiofficial.github.io/rsa/logos/humana.png"
  },
  {
    "slug": "humana-value-choice-h7617-032-ppo",
    "name": "Humana Value Choice H7617-032 (PPO)",
    "carrier": "Humana",
    "plan_type": "Medicare Advantage Prescription Drug PPO",
    "cms_plan_type": "MAPD",
    "contract_id": "H7617",
    "plan_id": "32",
    "snp": false,
    "premium": 0.0,
    "part_c_premium": 0.0,
    "part_d_premium": 0.0,
    "moop": 8950.0,
    "part_d_deductible": 615.0,
    "primary_care_copay": "$0",
    "specialist_copay": "$10 copay",
    "er_copay": "",
    "urgent_care_copay": "$50 copay",
    "telehealth_copay": "$0 copay",
    "dme_coinsurance": "$0",
    "dental_annual_max": 75.0,
    "hearing_aid_allowance": "$999",
    "fitness_program": "SilverSneakers",
    "transportation_trips": "",
    "otc_frequency": "Quarterly",
    "offers_part_d": true,
    "overall_stars": 5,
    "part_c_stars": 5,
    "part_d_stars": 4,
    "summary_of_benefits_url": "https://s3.amazonaws.com/webflow-prod-assets/698622c974c0ac921982c3e3/69a397d3ba0a82847c7629d0_Summary-of-Benefits.pdf",
    "evidence_of_coverage_url": "https://s3.amazonaws.com/webflow-prod-assets/698622c974c0ac921982c3e3/69a397d5354b439bb7d8128f_Evidence-of-Coverage.pdf",
    "counties": [],
    "logo_url": "https://papiofficial.github.io/rsa/logos/humana.png",
    "otc_credit": "$60",
    "vision_allowance": "$150"
  },
  {
    "slug": "humanachoice-giveback-h5216-430-ppo",
    "name": "HumanaChoice Giveback H5216-430 (PPO)",
    "carrier": "Humana",
    "plan_type": "Medicare Advantage PPO",
    "cms_plan_type": "Local PPO",
    "contract_id": "H5216",
    "plan_id": "430",
    "snp": false,
    "premium": 0.0,
    "part_c_premium": 0.0,
    "part_d_premium": 0.0,
    "moop": 9450.0,
    "part_d_deductible": 615.0,
    "primary_care_copay": "$0",
    "specialist_copay": "$40 copay",
    "er_copay": "$115 copay",
    "urgent_care_copay": "$40 copay",
    "telehealth_copay": "$0 copay",
    "dme_coinsurance": "$0",
    "dental_annual_max": 75.0,
    "hearing_aid_allowance": "$999",
    "fitness_program": "SilverSneakers",
    "transportation_trips": "",
    "otc_frequency": "",
    "offers_part_d": true,
    "overall_stars": 4,
    "part_c_stars": 4,
    "part_d_stars": 4,
    "summary_of_benefits_url": "https://s3.amazonaws.com/webflow-prod-assets/698622c974c0ac921982c3e3/69a3a17df75055c5b6d8e2f0_Summary-of-Benefits.pdf",
    "evidence_of_coverage_url": "https://s3.amazonaws.com/webflow-prod-assets/698622c974c0ac921982c3e3/69a3a17fc4ee1d555d9b69fd_Evidence-of-Coverage.pdf",
    "counties": [],
    "logo_url": "https://papiofficial.github.io/rsa/logos/humana.png"
  },
  {
    "slug": "humanachoice-h5216-048-ppo",
    "name": "HumanaChoice H5216-048 (PPO)",
    "carrier": "Humana",
    "plan_type": "Medicare Advantage PPO",
    "cms_plan_type": "Local PPO",
    "contract_id": "H5216",
    "plan_id": "48",
    "snp": false,
    "premium": 118.0,
    "part_c_premium": 52.0,
    "part_d_premium": 66.0,
    "moop": 6700.0,
    "part_d_deductible": 590.0,
    "primary_care_copay": "$0 copay",
    "specialist_copay": "$30 copay",
    "er_copay": "$95 copay",
    "urgent_care_copay": "$25 copay",
    "telehealth_copay": "$0 copay",
    "dme_coinsurance": "",
    "dental_annual_max": null,
    "hearing_aid_allowance": null,
    "fitness_program": "SilverSneakers",
    "transportation_trips": "",
    "otc_frequency": "Per Quarter",
    "offers_part_d": true,
    "overall_stars": 4,
    "part_c_stars": 4,
    "part_d_stars": 4,
    "summary_of_benefits_url": "",
    "evidence_of_coverage_url": "",
    "counties": [],
    "logo_url": "https://papiofficial.github.io/rsa/logos/humana.png"
  },
  {
    "slug": "humanachoice-h5216-131-ppo",
    "name": "HumanaChoice H5216-131 (PPO)",
    "carrier": "Humana",
    "plan_type": "Medicare Advantage PPO",
    "cms_plan_type": "Local PPO",
    "contract_id": "H5216",
    "plan_id": "131",
    "snp": false,
    "premium": 0.0,
    "part_c_premium": 0.0,
    "part_d_premium": 0.0,
    "moop": 5500.0,
    "part_d_deductible": 0.0,
    "primary_care_copay": "$0 copay",
    "specialist_copay": "$10 copay",
    "er_copay": "$110 copay",
    "urgent_care_copay": "$25 copay",
    "telehealth_copay": "",
    "dme_coinsurance": "",
    "dental_annual_max": null,
    "hearing_aid_allowance": null,
    "fitness_program": "SilverSneakers",
    "transportation_trips": "",
    "otc_frequency": "",
    "offers_part_d": true,
    "overall_stars": 4,
    "part_c_stars": 4,
    "part_d_stars": 4,
    "summary_of_benefits_url": "",
    "evidence_of_coverage_url": "",
    "counties": [],
    "logo_url": "https://papiofficial.github.io/rsa/logos/humana.png"
  },
  {
    "slug": "humanachoice-h7617-016-ppo",
    "name": "HumanaChoice H7617-016 (PPO)",
    "carrier": "Humana",
    "plan_type": "Medicare Advantage Prescription Drug PPO",
    "cms_plan_type": "MAPD",
    "contract_id": "H7617",
    "plan_id": "16",
    "snp": false,
    "premium": 87.0,
    "part_c_premium": 61.7,
    "part_d_premium": 25.3,
    "moop": 10100.0,
    "part_d_deductible": 615.0,
    "primary_care_copay": "$0",
    "specialist_copay": "$35 copay",
    "er_copay": "",
    "urgent_care_copay": "$50 copay",
    "telehealth_copay": "$0 copay",
    "dme_coinsurance": "$0",
    "dental_annual_max": 1000.0,
    "hearing_aid_allowance": "$999",
    "fitness_program": "SilverSneakers",
    "transportation_trips": "",
    "otc_frequency": "",
    "offers_part_d": true,
    "overall_stars": 5,
    "part_c_stars": 5,
    "part_d_stars": 4,
    "summary_of_benefits_url": "https://s3.amazonaws.com/webflow-prod-assets/698622c974c0ac921982c3e3/69a397bb05b730b23c2c938d_Summary-of-Benefits.pdf",
    "evidence_of_coverage_url": "https://s3.amazonaws.com/webflow-prod-assets/698622c974c0ac921982c3e3/69a397bd05b730b23c2c948a_Evidence-of-Coverage.pdf",
    "counties": [],
    "logo_url": "https://papiofficial.github.io/rsa/logos/humana.png",
    "vision_allowance": "$100"
  },
  {
    "slug": "humanachoice-snp-de-h5216-296-ppo-d-snp",
    "name": "HumanaChoice SNP-DE H5216-296 (PPO D-SNP)",
    "carrier": "Humana",
    "plan_type": "Medicare Advantage PPO",
    "cms_plan_type": "Local PPO",
    "contract_id": "H5216",
    "plan_id": "296",
    "snp": true,
    "premium": 0.0,
    "part_c_premium": 0.0,
    "part_d_premium": 40.5,
    "moop": 13900.0,
    "part_d_deductible": 615.0,
    "primary_care_copay": "$0",
    "specialist_copay": "$0 copay",
    "er_copay": "$0 copay",
    "urgent_care_copay": "$0 copay",
    "telehealth_copay": "$0 copay",
    "dme_coinsurance": "$0",
    "dental_annual_max": 0.0,
    "hearing_aid_allowance": 0.0,
    "fitness_program": "SilverSneakers",
    "transportation_trips": "",
    "otc_frequency": "",
    "offers_part_d": true,
    "overall_stars": 4,
    "part_c_stars": 4,
    "part_d_stars": 4,
    "summary_of_benefits_url": "https://s3.amazonaws.com/webflow-prod-assets/698622c974c0ac921982c3e3/69a3a170cfd8e4e75ebb6f90_Summary-of-Benefits.pdf",
    "evidence_of_coverage_url": "https://s3.amazonaws.com/webflow-prod-assets/698622c974c0ac921982c3e3/69a3a173725736fc7b89dd72_Evidence-of-Coverage.pdf",
    "counties": [],
    "logo_url": "https://papiofficial.github.io/rsa/logos/humana.png"
  },
  {
    "slug": "humanachoice-snp-de-h7617-038-ppo-d-snp",
    "name": "HumanaChoice SNP-DE H7617-038 (PPO D-SNP)",
    "carrier": "Humana",
    "plan_type": "Medicare Advantage Prescription Drug PPO",
    "cms_plan_type": "MAPD",
    "contract_id": "H7617",
    "plan_id": "38",
    "snp": true,
    "premium": 0.0,
    "part_c_premium": 0.0,
    "part_d_premium": 29.7,
    "moop": 9250.0,
    "part_d_deductible": 615.0,
    "primary_care_copay": "$0",
    "specialist_copay": "$0 copay",
    "er_copay": "$0 copay",
    "urgent_care_copay": "$0 copay",
    "telehealth_copay": "$0 copay",
    "dme_coinsurance": "$0",
    "dental_annual_max": 0.0,
    "hearing_aid_allowance": 0.0,
    "fitness_program": "SilverSneakers",
    "transportation_trips": "",
    "otc_frequency": "",
    "offers_part_d": true,
    "overall_stars": 5,
    "part_c_stars": 5,
    "part_d_stars": 4,
    "summary_of_benefits_url": "https://s3.amazonaws.com/webflow-prod-assets/698622c974c0ac921982c3e3/69a397db354b439bb7d8156e_Summary-of-Benefits.pdf",
    "evidence_of_coverage_url": "https://s3.amazonaws.com/webflow-prod-assets/698622c974c0ac921982c3e3/69a397dd3db42179d091d2bc_Evidence-of-Coverage.pdf",
    "counties": [],
    "logo_url": "https://papiofficial.github.io/rsa/logos/humana.png"
  },
  {
    "slug": "molina-medicare-complete-care-hmo-d-snp-h5628-001",
    "name": "Molina Medicare Complete Care (HMO D-SNP)",
    "carrier": "Molina Healthcare of Utah & Idaho",
    "plan_type": "Medicare Advantage HMO",
    "cms_plan_type": "HMO/HMOPOS",
    "contract_id": "H5628",
    "plan_id": "1",
    "snp": true,
    "premium": 0.0,
    "part_c_premium": 0.0,
    "part_d_premium": 40.8,
    "moop": 9250.0,
    "part_d_deductible": 615.0,
    "primary_care_copay": "",
    "specialist_copay": "",
    "er_copay": "$0 copay",
    "urgent_care_copay": "",
    "telehealth_copay": "",
    "dme_coinsurance": "",
    "dental_annual_max": 1000.0,
    "hearing_aid_allowance": 0.0,
    "fitness_program": "Silver&Fit",
    "transportation_trips": "Not covered",
    "otc_frequency": "Monthly",
    "offers_part_d": true,
    "overall_stars": 3,
    "part_c_stars": 3,
    "part_d_stars": 3,
    "summary_of_benefits_url": "https://s3.amazonaws.com/webflow-prod-assets/698622c974c0ac921982c3e3/69a3a18910f2fb0e8f1d10b9_Summary-of-Benefits.pdf",
    "evidence_of_coverage_url": "",
    "counties": [],
    "logo_url": "https://papiofficial.github.io/rsa/logos/molina.png"
  },
  {
    "slug": "molina-medicare-complete-care-select-hmo-d-snp-h5628-012",
    "name": "Molina Medicare Complete Care Select (HMO D-SNP)",
    "carrier": "Molina Healthcare of Utah & Idaho",
    "plan_type": "Medicare Advantage HMO",
    "cms_plan_type": "HMO/HMOPOS",
    "contract_id": "H5628",
    "plan_id": "12",
    "snp": true,
    "premium": 0.0,
    "part_c_premium": 0.0,
    "part_d_premium": 17.7,
    "moop": 9250.0,
    "part_d_deductible": 615.0,
    "primary_care_copay": "",
    "specialist_copay": "",
    "er_copay": "$100 copay",
    "urgent_care_copay": "",
    "telehealth_copay": "",
    "dme_coinsurance": "",
    "dental_annual_max": 1200.0,
    "hearing_aid_allowance": 30.0,
    "fitness_program": "Silver&Fit",
    "transportation_trips": "",
    "otc_frequency": "Monthly",
    "offers_part_d": true,
    "overall_stars": 3,
    "part_c_stars": 3,
    "part_d_stars": 3,
    "summary_of_benefits_url": "https://s3.amazonaws.com/webflow-prod-assets/698622c974c0ac921982c3e3/69a3a18d10f2fb0e8f1d1389_Summary-of-Benefits.pdf",
    "evidence_of_coverage_url": "",
    "counties": [],
    "logo_url": "https://papiofficial.github.io/rsa/logos/molina.png"
  },
  {
    "slug": "regence-medadvantage-rx-classic-ppo-h4605-002",
    "name": "Regence MedAdvantage + Rx Classic (PPO)",
    "carrier": "Regence BlueCross BlueShield of Utah",
    "plan_type": "Medicare Advantage PPO",
    "cms_plan_type": "Local PPO",
    "contract_id": "H4605",
    "plan_id": "2",
    "snp": false,
    "premium": 41.0,
    "part_c_premium": 19.2,
    "part_d_premium": 21.8,
    "moop": 6200.0,
    "part_d_deductible": 100.0,
    "primary_care_copay": "$0 copay",
    "specialist_copay": "$40 copay",
    "er_copay": "$130 copay",
    "urgent_care_copay": "$50 copay",
    "telehealth_copay": "$35 copay",
    "dme_coinsurance": "0% coinsurance",
    "dental_annual_max": 6200.0,
    "hearing_aid_allowance": 0.0,
    "fitness_program": "Included (see plan details)",
    "transportation_trips": "Not covered",
    "otc_frequency": "",
    "offers_part_d": true,
    "overall_stars": 4,
    "part_c_stars": 5,
    "part_d_stars": 4,
    "summary_of_benefits_url": "",
    "evidence_of_coverage_url": "",
    "counties": [],
    "logo_url": "https://papiofficial.github.io/rsa/logos/regence.png"
  },
  {
    "slug": "regence-medadvantage-rx-enhanced-ppo-h4605-004",
    "name": "Regence MedAdvantage + Rx Enhanced (PPO)",
    "carrier": "Regence BlueCross BlueShield of Utah",
    "plan_type": "Medicare Advantage PPO",
    "cms_plan_type": "Local PPO",
    "contract_id": "H4605",
    "plan_id": "4",
    "snp": false,
    "premium": 130.0,
    "part_c_premium": 108.5,
    "part_d_premium": 21.5,
    "moop": 5000.0,
    "part_d_deductible": 0.0,
    "primary_care_copay": "$0",
    "specialist_copay": "",
    "er_copay": "",
    "urgent_care_copay": "",
    "telehealth_copay": "",
    "dme_coinsurance": "",
    "dental_annual_max": null,
    "hearing_aid_allowance": null,
    "fitness_program": "Silver&Fit",
    "transportation_trips": "Not covered",
    "otc_frequency": "",
    "offers_part_d": true,
    "overall_stars": 4,
    "part_c_stars": 5,
    "part_d_stars": 4,
    "summary_of_benefits_url": "",
    "evidence_of_coverage_url": "",
    "counties": [],
    "logo_url": "https://papiofficial.github.io/rsa/logos/regence.png"
  },
  {
    "slug": "regence-valiance-ppo-h4605-001",
    "name": "Regence Valiance (PPO)",
    "carrier": "Regence BlueCross BlueShield of Utah",
    "plan_type": "Medicare Advantage PPO",
    "cms_plan_type": "Local PPO",
    "contract_id": "H4605",
    "plan_id": "1",
    "snp": false,
    "premium": null,
    "part_c_premium": 0.0,
    "part_d_premium": null,
    "moop": 4500.0,
    "part_d_deductible": null,
    "primary_care_copay": "$0 copay",
    "specialist_copay": "$30 copay",
    "er_copay": "",
    "urgent_care_copay": "$50 copay",
    "telehealth_copay": "",
    "dme_coinsurance": "0% coinsurance",
    "dental_annual_max": 4500.0,
    "hearing_aid_allowance": 0.0,
    "fitness_program": "",
    "transportation_trips": "",
    "otc_frequency": "",
    "offers_part_d": false,
    "overall_stars": 4,
    "part_c_stars": 5,
    "part_d_stars": 4,
    "summary_of_benefits_url": "",
    "evidence_of_coverage_url": "",
    "counties": [],
    "logo_url": "https://papiofficial.github.io/rsa/logos/regence.png"
  },
  {
    "slug": "select-health-medicare-kroger-hmo-h1994-022",
    "name": "Select Health Medicare + Kroger (HMO)",
    "carrier": "Select Health",
    "plan_type": "Medicare Advantage HMO-POS",
    "cms_plan_type": "HMO/HMOPOS",
    "contract_id": "H1994",
    "plan_id": "22",
    "snp": false,
    "premium": 0.0,
    "part_c_premium": 0.0,
    "part_d_premium": 0.0,
    "moop": 5700.0,
    "part_d_deductible": 0.0,
    "primary_care_copay": "$0 copay",
    "specialist_copay": "$45 copay",
    "er_copay": "$130 copay",
    "urgent_care_copay": "$50 copay",
    "telehealth_copay": "$0 copay",
    "dme_coinsurance": "0% coinsurance",
    "dental_annual_max": 0.0,
    "hearing_aid_allowance": 699.0,
    "fitness_program": "",
    "transportation_trips": "",
    "otc_frequency": "per month",
    "offers_part_d": true,
    "overall_stars": 4,
    "part_c_stars": 4,
    "part_d_stars": 4,
    "summary_of_benefits_url": "https://s3.amazonaws.com/webflow-prod-assets/698622c974c0ac921982c3e3/69a3b0e786d8eeec0cf7197f_Summary-of-Benefits.pdf",
    "evidence_of_coverage_url": "https://s3.amazonaws.com/webflow-prod-assets/698622c974c0ac921982c3e3/69a3b0e4afd4b4920347eeb7_Evidence-of-Coverage.pdf",
    "counties": [],
    "logo_url": "https://papiofficial.github.io/rsa/logos/selecthealth.png"
  },
  {
    "slug": "select-health-medicare-choice-ppo-h2246-018",
    "name": "Select Health Medicare Choice (PPO)",
    "carrier": "Select Health",
    "plan_type": "Medicare Advantage PPO",
    "cms_plan_type": "Local PPO",
    "contract_id": "H2246",
    "plan_id": "18",
    "snp": false,
    "premium": 14.0,
    "part_c_premium": 0.0,
    "part_d_premium": 14.0,
    "moop": 5700.0,
    "part_d_deductible": 100.0,
    "primary_care_copay": "",
    "specialist_copay": "",
    "er_copay": "",
    "urgent_care_copay": "",
    "telehealth_copay": "",
    "dme_coinsurance": "",
    "dental_annual_max": null,
    "hearing_aid_allowance": null,
    "fitness_program": "",
    "transportation_trips": "",
    "otc_frequency": "",
    "offers_part_d": true,
    "overall_stars": 4,
    "part_c_stars": 4,
    "part_d_stars": 3,
    "summary_of_benefits_url": "",
    "evidence_of_coverage_url": "",
    "counties": [],
    "logo_url": "https://papiofficial.github.io/rsa/logos/selecthealth.png"
  },
  {
    "slug": "select-health-medicare-classic-hmo-h1994-002",
    "name": "Select Health Medicare Classic (HMO)",
    "carrier": "Select Health",
    "plan_type": "Medicare Advantage HMO-POS",
    "cms_plan_type": "HMO/HMOPOS",
    "contract_id": "H1994",
    "plan_id": "2",
    "snp": false,
    "premium": 59.0,
    "part_c_premium": 0.0,
    "part_d_premium": 59.0,
    "moop": 6700.0,
    "part_d_deductible": 200.0,
    "primary_care_copay": "",
    "specialist_copay": "",
    "er_copay": "",
    "urgent_care_copay": "",
    "telehealth_copay": "",
    "dme_coinsurance": "",
    "dental_annual_max": null,
    "hearing_aid_allowance": null,
    "fitness_program": "",
    "transportation_trips": "",
    "otc_frequency": "",
    "offers_part_d": true,
    "overall_stars": 4,
    "part_c_stars": 4,
    "part_d_stars": 4,
    "summary_of_benefits_url": "",
    "evidence_of_coverage_url": "",
    "counties": [],
    "logo_url": "https://papiofficial.github.io/rsa/logos/selecthealth.png"
  },
  {
    "slug": "select-health-medicare-dual-hmo-d-snp-h1994-015",
    "name": "Select Health Medicare Dual (HMO D-SNP)",
    "carrier": "Select Health",
    "plan_type": "Medicare Advantage HMO-POS",
    "cms_plan_type": "HMO/HMOPOS",
    "contract_id": "H1994",
    "plan_id": "15",
    "snp": true,
    "premium": 54.6,
    "part_c_premium": 0.0,
    "part_d_premium": 54.6,
    "moop": 8850.0,
    "part_d_deductible": 590.0,
    "primary_care_copay": "$0 copay",
    "specialist_copay": "$0 copay",
    "er_copay": "$0 copay",
    "urgent_care_copay": "$0 copay",
    "telehealth_copay": "$0 copay",
    "dme_coinsurance": "$0",
    "dental_annual_max": 0.0,
    "hearing_aid_allowance": 0.0,
    "fitness_program": "",
    "transportation_trips": "",
    "otc_frequency": "",
    "offers_part_d": true,
    "overall_stars": 4,
    "part_c_stars": 4,
    "part_d_stars": 4,
    "summary_of_benefits_url": "",
    "evidence_of_coverage_url": "https://s3.amazonaws.com/webflow-prod-assets/698622c974c0ac921982c3e3/69a3b0cd3dc3426c8ad04b98_Evidence-of-Coverage.pdf",
    "counties": [],
    "logo_url": "https://papiofficial.github.io/rsa/logos/selecthealth.png"
  },
  {
    "slug": "select-health-medicare-enhanced-hmo-h1994-007",
    "name": "Select Health Medicare Enhanced (HMO)",
    "carrier": "Select Health",
    "plan_type": "Medicare Advantage HMO-POS",
    "cms_plan_type": "HMO/HMOPOS",
    "contract_id": "H1994",
    "plan_id": "7",
    "snp": false,
    "premium": 63.0,
    "part_c_premium": 0.0,
    "part_d_premium": 63.0,
    "moop": 4700.0,
    "part_d_deductible": 0.0,
    "primary_care_copay": "",
    "specialist_copay": "",
    "er_copay": "",
    "urgent_care_copay": "",
    "telehealth_copay": "",
    "dme_coinsurance": "",
    "dental_annual_max": null,
    "hearing_aid_allowance": null,
    "fitness_program": "",
    "transportation_trips": "",
    "otc_frequency": "",
    "offers_part_d": true,
    "overall_stars": 4,
    "part_c_stars": 4,
    "part_d_stars": 4,
    "summary_of_benefits_url": "",
    "evidence_of_coverage_url": "",
    "counties": [],
    "logo_url": "https://papiofficial.github.io/rsa/logos/selecthealth.png"
  },
  {
    "slug": "select-health-medicare-essential-hmo-h1994-001",
    "name": "Select Health Medicare Essential (HMO)",
    "carrier": "Select Health",
    "plan_type": "Medicare Advantage HMO-POS",
    "cms_plan_type": "HMO/HMOPOS",
    "contract_id": "H1994",
    "plan_id": "1",
    "snp": false,
    "premium": 0.0,
    "part_c_premium": 0.0,
    "part_d_premium": 0.0,
    "moop": 4900.0,
    "part_d_deductible": 200.0,
    "primary_care_copay": "$0 copay",
    "specialist_copay": "$30 copay",
    "er_copay": "$130 copay",
    "urgent_care_copay": "$40 copay",
    "telehealth_copay": "$0 copay",
    "dme_coinsurance": "0% coinsurance",
    "dental_annual_max": null,
    "hearing_aid_allowance": 299.0,
    "fitness_program": "Silver&Fit",
    "transportation_trips": "",
    "otc_frequency": "",
    "offers_part_d": true,
    "overall_stars": 4,
    "part_c_stars": 4,
    "part_d_stars": 4,
    "summary_of_benefits_url": "https://s3.amazonaws.com/webflow-prod-assets/698622c974c0ac921982c3e3/69a3b0d4afd4b4920347e350_Summary-of-Benefits.pdf",
    "evidence_of_coverage_url": "https://s3.amazonaws.com/webflow-prod-assets/698622c974c0ac921982c3e3/69a3b0d186d8eeec0cf71074_Evidence-of-Coverage.pdf",
    "counties": [],
    "logo_url": "https://papiofficial.github.io/rsa/logos/selecthealth.png"
  },
  {
    "slug": "select-health-medicare-essential-hmo-h1994-017",
    "name": "Select Health Medicare Essential (HMO)",
    "carrier": "Select Health",
    "plan_type": "Medicare Advantage HMO-POS",
    "cms_plan_type": "HMO/HMOPOS",
    "contract_id": "H1994",
    "plan_id": "17",
    "snp": false,
    "premium": 0.0,
    "part_c_premium": 0.0,
    "part_d_premium": 0.0,
    "moop": 5700.0,
    "part_d_deductible": 200.0,
    "primary_care_copay": "$0 copay",
    "specialist_copay": "$35 copay",
    "er_copay": "$130 copay",
    "urgent_care_copay": "$35 copay",
    "telehealth_copay": "$0 copay",
    "dme_coinsurance": "0% coinsurance",
    "dental_annual_max": null,
    "hearing_aid_allowance": 699.0,
    "fitness_program": "Silver&Fit",
    "transportation_trips": "",
    "otc_frequency": "per quarter",
    "offers_part_d": true,
    "overall_stars": 4,
    "part_c_stars": 4,
    "part_d_stars": 4,
    "summary_of_benefits_url": "https://s3.amazonaws.com/webflow-prod-assets/698622c974c0ac921982c3e3/69a3b0da5386c90d9a644b56_Summary-of-Benefits.pdf",
    "evidence_of_coverage_url": "https://s3.amazonaws.com/webflow-prod-assets/698622c974c0ac921982c3e3/69a3b0d7e64f119c11fb4d1b_Evidence-of-Coverage.pdf",
    "counties": [],
    "logo_url": "https://papiofficial.github.io/rsa/logos/selecthealth.png"
  },
  {
    "slug": "select-health-medicare-norx-hmo-h1994-016",
    "name": "Select Health Medicare NoRx (HMO)",
    "carrier": "Select Health",
    "plan_type": "Medicare Advantage HMO-POS",
    "cms_plan_type": "HMO/HMOPOS",
    "contract_id": "H1994",
    "plan_id": "16",
    "snp": false,
    "premium": null,
    "part_c_premium": 0.0,
    "part_d_premium": null,
    "moop": 6700.0,
    "part_d_deductible": null,
    "primary_care_copay": "$0 copay",
    "specialist_copay": "$50 copay",
    "er_copay": "$130 copay",
    "urgent_care_copay": "$50 copay",
    "telehealth_copay": "$0 copay",
    "dme_coinsurance": "20% coinsurance",
    "dental_annual_max": 300.0,
    "hearing_aid_allowance": 299.0,
    "fitness_program": "",
    "transportation_trips": "",
    "otc_frequency": "Per Year",
    "offers_part_d": false,
    "overall_stars": 4,
    "part_c_stars": 4,
    "part_d_stars": 4,
    "summary_of_benefits_url": "https://s3.amazonaws.com/webflow-prod-assets/698622c974c0ac921982c3e3/69a3b0e13da85fb02fc04b17_Summary-of-Benefits.pdf",
    "evidence_of_coverage_url": "https://s3.amazonaws.com/webflow-prod-assets/698622c974c0ac921982c3e3/69a3b0de2b0a34565fe325f7_Evidence-of-Coverage.pdf",
    "counties": [],
    "logo_url": "https://papiofficial.github.io/rsa/logos/selecthealth.png"
  },
  {
    "slug": "aarp-medicare-advantage-essentials-from-uhc-ut-4-hmo-pos-h4604-011",
    "name": "AARP Medicare Advantage Essentials from UHC UT-4 (HMO-POS)",
    "carrier": "UnitedHealthcare",
    "plan_type": "Medicare Advantage HMO-POS",
    "cms_plan_type": "HMO/HMOPOS",
    "contract_id": "H4604",
    "plan_id": "11",
    "snp": false,
    "premium": 0.0,
    "part_c_premium": 0.0,
    "part_d_premium": 0.0,
    "moop": 5200.0,
    "part_d_deductible": 615.0,
    "primary_care_copay": "$0 copay",
    "specialist_copay": "$40 copay",
    "er_copay": "$130 copay",
    "urgent_care_copay": "$50 copay",
    "telehealth_copay": "",
    "dme_coinsurance": "0% coinsurance",
    "dental_annual_max": null,
    "hearing_aid_allowance": 199.0,
    "fitness_program": "",
    "transportation_trips": "Not covered",
    "otc_frequency": "",
    "offers_part_d": true,
    "overall_stars": 4,
    "part_c_stars": 4,
    "part_d_stars": 5,
    "summary_of_benefits_url": "https://s3.amazonaws.com/webflow-prod-assets/698622c974c0ac921982c3e3/69a3a1b03db42179d096046d_Summary-of-Benefits.pdf",
    "evidence_of_coverage_url": "https://s3.amazonaws.com/webflow-prod-assets/698622c974c0ac921982c3e3/69a3a1b19e88f17011fef376_Evidence-of-Coverage.pdf",
    "counties": [],
    "logo_url": "https://papiofficial.github.io/rsa/logos/unitedhealthcare.png"
  },
  {
    "slug": "aarp-medicare-advantage-extras-valuerx-ut-7-hmo-pos-h4604-018",
    "name": "AARP Medicare Advantage Extras ValueRx UT-7 (HMO-POS)",
    "carrier": "UnitedHealthcare",
    "plan_type": "Medicare Advantage HMO-POS",
    "cms_plan_type": "HMO/HMOPOS",
    "contract_id": "H4604",
    "plan_id": "18",
    "snp": false,
    "premium": 0.0,
    "part_c_premium": 0.0,
    "part_d_premium": 0.0,
    "moop": 6700.0,
    "part_d_deductible": 615.0,
    "primary_care_copay": "$0 copay",
    "specialist_copay": "$55 copay",
    "er_copay": "$130 copay",
    "urgent_care_copay": "$50 copay",
    "telehealth_copay": "",
    "dme_coinsurance": "0% coinsurance",
    "dental_annual_max": 3000.0,
    "hearing_aid_allowance": 199.0,
    "fitness_program": "",
    "transportation_trips": "Not covered",
    "otc_frequency": "",
    "offers_part_d": true,
    "overall_stars": 4,
    "part_c_stars": 4,
    "part_d_stars": 5,
    "summary_of_benefits_url": "https://s3.amazonaws.com/webflow-prod-assets/698622c974c0ac921982c3e3/69a3a1ba48e4ba8cfbccd9fd_Summary-of-Benefits.pdf",
    "evidence_of_coverage_url": "https://s3.amazonaws.com/webflow-prod-assets/698622c974c0ac921982c3e3/69a3a1bc4bc8854de72842bf_Evidence-of-Coverage.pdf",
    "counties": [],
    "logo_url": "https://papiofficial.github.io/rsa/logos/unitedhealthcare.png"
  },
  {
    "slug": "aarp-medicare-advantage-giveback-from-uhc-ut-9-ppo-h2001-131",
    "name": "AARP Medicare Advantage Giveback from UHC UT-9 (PPO)",
    "carrier": "UnitedHealthcare",
    "plan_type": "Medicare Advantage PPO",
    "cms_plan_type": "Local PPO",
    "contract_id": "H2001",
    "plan_id": "131",
    "snp": false,
    "premium": 0.0,
    "part_c_premium": 0.0,
    "part_d_premium": 0.0,
    "moop": 13900.0,
    "part_d_deductible": 615.0,
    "primary_care_copay": "$0 copay",
    "specialist_copay": "$65 copay",
    "er_copay": "$115 copay",
    "urgent_care_copay": "$40 copay",
    "telehealth_copay": "",
    "dme_coinsurance": "0% coinsurance",
    "dental_annual_max": null,
    "hearing_aid_allowance": 199.0,
    "fitness_program": "",
    "transportation_trips": "Not covered",
    "otc_frequency": "",
    "offers_part_d": true,
    "overall_stars": 5,
    "part_c_stars": 4,
    "part_d_stars": 5,
    "summary_of_benefits_url": "https://s3.amazonaws.com/webflow-prod-assets/698622c974c0ac921982c3e3/69a3a1a14bc8854de728381b_Summary-of-Benefits.pdf",
    "evidence_of_coverage_url": "https://s3.amazonaws.com/webflow-prod-assets/698622c974c0ac921982c3e3/69a3a1a24bc8854de728391b_Evidence-of-Coverage.pdf",
    "counties": [],
    "logo_url": "https://papiofficial.github.io/rsa/logos/unitedhealthcare.png"
  },
  {
    "slug": "aarp-medicare-advantage-patriot-no-rx-ut-ma01-hmo-pos-h4604-005",
    "name": "AARP Medicare Advantage Patriot No Rx UT-MA01 (HMO-POS)",
    "carrier": "UnitedHealthcare",
    "plan_type": "Medicare Advantage HMO-POS",
    "cms_plan_type": "HMO/HMOPOS",
    "contract_id": "H4604",
    "plan_id": "5",
    "snp": false,
    "premium": 0.0,
    "part_c_premium": 0.0,
    "part_d_premium": null,
    "moop": 6700.0,
    "part_d_deductible": 615.0,
    "primary_care_copay": "$0 copay",
    "specialist_copay": "$60 copay",
    "er_copay": "$130 copay",
    "urgent_care_copay": "$50 copay",
    "telehealth_copay": "",
    "dme_coinsurance": "0% coinsurance",
    "dental_annual_max": 1500.0,
    "hearing_aid_allowance": 199.0,
    "fitness_program": "",
    "transportation_trips": "Not covered",
    "otc_frequency": "",
    "offers_part_d": false,
    "overall_stars": 4,
    "part_c_stars": 4,
    "part_d_stars": 5,
    "summary_of_benefits_url": "https://s3.amazonaws.com/webflow-prod-assets/698622c974c0ac921982c3e3/69a3a1abcfd8e4e75ebb98b9_Summary-of-Benefits.pdf",
    "evidence_of_coverage_url": "https://s3.amazonaws.com/webflow-prod-assets/698622c974c0ac921982c3e3/69a3a1ac22bf1fc3b1efbbf0_Evidence-of-Coverage.pdf",
    "counties": [],
    "logo_url": "https://papiofficial.github.io/rsa/logos/unitedhealthcare.png"
  },
  {
    "slug": "aarp-medicare-advantage-from-uhc-ut-0001-ppo-h2001-017",
    "name": "AARP Medicare Advantage from UHC UT-0001 (PPO)",
    "carrier": "UnitedHealthcare",
    "plan_type": "Medicare Advantage PPO",
    "cms_plan_type": "Local PPO",
    "contract_id": "H2001",
    "plan_id": "17",
    "snp": false,
    "premium": 28.0,
    "part_c_premium": 0.4,
    "part_d_premium": 27.6,
    "moop": 4900.0,
    "part_d_deductible": 420.0,
    "primary_care_copay": "$0 copay",
    "specialist_copay": "$40 copay",
    "er_copay": "$0 copay",
    "urgent_care_copay": "$0 copay",
    "telehealth_copay": "",
    "dme_coinsurance": "0% coinsurance",
    "dental_annual_max": 1000.0,
    "hearing_aid_allowance": 199.0,
    "fitness_program": "Included (see plan details)",
    "transportation_trips": "Not covered",
    "otc_frequency": "",
    "offers_part_d": true,
    "overall_stars": 4,
    "part_c_stars": 4,
    "part_d_stars": 5,
    "summary_of_benefits_url": "",
    "evidence_of_coverage_url": "",
    "counties": [],
    "logo_url": "https://papiofficial.github.io/rsa/logos/unitedhealthcare.png"
  },
  {
    "slug": "aarp-medicare-advantage-from-uhc-ut-0002-ppo-h2001-023",
    "name": "AARP Medicare Advantage from UHC UT-0002 (PPO)",
    "carrier": "UnitedHealthcare",
    "plan_type": "Medicare Advantage PPO",
    "cms_plan_type": "Local PPO",
    "contract_id": "H2001",
    "plan_id": "23",
    "snp": false,
    "premium": 0.0,
    "part_c_premium": 0.0,
    "part_d_premium": 0.0,
    "moop": 5500.0,
    "part_d_deductible": 420.0,
    "primary_care_copay": "$0 copay",
    "specialist_copay": "$45 copay",
    "er_copay": "$0 copay",
    "urgent_care_copay": "$0 copay",
    "telehealth_copay": "",
    "dme_coinsurance": "0% coinsurance",
    "dental_annual_max": null,
    "hearing_aid_allowance": 199.0,
    "fitness_program": "Included (see plan details)",
    "transportation_trips": "Not covered",
    "otc_frequency": "",
    "offers_part_d": true,
    "overall_stars": 4,
    "part_c_stars": 4,
    "part_d_stars": 5,
    "summary_of_benefits_url": "",
    "evidence_of_coverage_url": "",
    "counties": [],
    "logo_url": "https://papiofficial.github.io/rsa/logos/unitedhealthcare.png"
  },
  {
    "slug": "aarp-medicare-advantage-from-uhc-ut-0003-hmo-pos-h4604-003",
    "name": "AARP Medicare Advantage from UHC UT-0003 (HMO-POS)",
    "carrier": "UnitedHealthcare",
    "plan_type": "Medicare Advantage HMO-POS",
    "cms_plan_type": "HMO/HMOPOS",
    "contract_id": "H4604",
    "plan_id": "3",
    "snp": false,
    "premium": 55.0,
    "part_c_premium": 11.4,
    "part_d_premium": 20.6,
    "moop": 4900.0,
    "part_d_deductible": 615.0,
    "primary_care_copay": "$0 copay",
    "specialist_copay": "$35 copay",
    "er_copay": "$130 copay",
    "urgent_care_copay": "$50 copay",
    "telehealth_copay": "",
    "dme_coinsurance": "0% coinsurance",
    "dental_annual_max": 2000.0,
    "hearing_aid_allowance": 199.0,
    "fitness_program": "",
    "transportation_trips": "Not covered",
    "otc_frequency": "",
    "offers_part_d": true,
    "overall_stars": 4,
    "part_c_stars": 4,
    "part_d_stars": 5,
    "summary_of_benefits_url": "https://s3.amazonaws.com/webflow-prod-assets/698622c974c0ac921982c3e3/69a3a1a6cfd8e4e75ebb94b9_Summary-of-Benefits.pdf",
    "evidence_of_coverage_url": "https://s3.amazonaws.com/webflow-prod-assets/698622c974c0ac921982c3e3/69a3a1a75386c90d9a624d57_Evidence-of-Coverage.pdf",
    "counties": [],
    "logo_url": "https://papiofficial.github.io/rsa/logos/unitedhealthcare.png"
  },
  {
    "slug": "aarp-medicare-advantage-from-uhc-ut-0005-hmo-pos-h4604-016",
    "name": "AARP Medicare Advantage from UHC UT-0005 (HMO-POS)",
    "carrier": "UnitedHealthcare",
    "plan_type": "Medicare Advantage HMO-POS",
    "cms_plan_type": "HMO/HMOPOS",
    "contract_id": "H4604",
    "plan_id": "16",
    "snp": false,
    "premium": 0.0,
    "part_c_premium": 0.0,
    "part_d_premium": 0.0,
    "moop": 4900.0,
    "part_d_deductible": 340.0,
    "primary_care_copay": "$0 copay",
    "specialist_copay": "$35 copay",
    "er_copay": "$0 copay",
    "urgent_care_copay": "$0 copay",
    "telehealth_copay": "",
    "dme_coinsurance": "0% coinsurance",
    "dental_annual_max": null,
    "hearing_aid_allowance": 199.0,
    "fitness_program": "Included (see plan details)",
    "transportation_trips": "Not covered",
    "otc_frequency": "",
    "offers_part_d": true,
    "overall_stars": 4,
    "part_c_stars": 4,
    "part_d_stars": 5,
    "summary_of_benefits_url": "",
    "evidence_of_coverage_url": "",
    "counties": [],
    "logo_url": "https://papiofficial.github.io/rsa/logos/unitedhealthcare.png"
  },
  {
    "slug": "aarp-medicare-advantage-from-uhc-ut-0008-ppo-h2001-128",
    "name": "AARP Medicare Advantage from UHC UT-0008 (PPO)",
    "carrier": "UnitedHealthcare",
    "plan_type": "Medicare Advantage PPO",
    "cms_plan_type": "Local PPO",
    "contract_id": "H2001",
    "plan_id": "128",
    "snp": false,
    "premium": 0.0,
    "part_c_premium": 0.0,
    "part_d_premium": 0.0,
    "moop": 10100.0,
    "part_d_deductible": 615.0,
    "primary_care_copay": "$0 copay",
    "specialist_copay": "$75 copay",
    "er_copay": "$130 copay",
    "urgent_care_copay": "$50 copay",
    "telehealth_copay": "",
    "dme_coinsurance": "0% coinsurance",
    "dental_annual_max": null,
    "hearing_aid_allowance": 199.0,
    "fitness_program": "",
    "transportation_trips": "Not covered",
    "otc_frequency": "",
    "offers_part_d": true,
    "overall_stars": 5,
    "part_c_stars": 4,
    "part_d_stars": 5,
    "summary_of_benefits_url": "https://s3.amazonaws.com/webflow-prod-assets/698622c974c0ac921982c3e3/69a3a19c7a28a9a8183a3e69_Summary-of-Benefits.pdf",
    "evidence_of_coverage_url": "https://s3.amazonaws.com/webflow-prod-assets/698622c974c0ac921982c3e3/69a3a19ddf7e93f9bf0e3e7d_Evidence-of-Coverage.pdf",
    "counties": [],
    "logo_url": "https://papiofficial.github.io/rsa/logos/unitedhealthcare.png"
  },
  {
    "slug": "uhc-complete-care-ut-6-hmo-pos-c-snp-h4604-017",
    "name": "UHC Complete Care UT-6 (HMO-POS C-SNP)",
    "carrier": "UnitedHealthcare",
    "plan_type": "Medicare Advantage HMO-POS",
    "cms_plan_type": "HMO/HMOPOS",
    "contract_id": "H4604",
    "plan_id": "17",
    "snp": true,
    "premium": 0.0,
    "part_c_premium": 0.0,
    "part_d_premium": 0.0,
    "moop": 5200.0,
    "part_d_deductible": 615.0,
    "primary_care_copay": "$0 copay",
    "specialist_copay": "$35 copay",
    "er_copay": "$130 copay",
    "urgent_care_copay": "$50 copay",
    "telehealth_copay": "",
    "dme_coinsurance": "0% coinsurance",
    "dental_annual_max": null,
    "hearing_aid_allowance": 199.0,
    "fitness_program": "",
    "transportation_trips": "",
    "otc_frequency": "",
    "offers_part_d": true,
    "overall_stars": 4,
    "part_c_stars": 4,
    "part_d_stars": 5,
    "summary_of_benefits_url": "https://s3.amazonaws.com/webflow-prod-assets/698622c974c0ac921982c3e3/69a3a1b591c29a96f75cb417_Summary-of-Benefits.pdf",
    "evidence_of_coverage_url": "https://s3.amazonaws.com/webflow-prod-assets/698622c974c0ac921982c3e3/69a3a1b74bc8854de7283fff_Evidence-of-Coverage.pdf",
    "counties": [],
    "logo_url": "https://papiofficial.github.io/rsa/logos/unitedhealthcare.png"
  },
  {
    "slug": "uhc-dual-complete-ut-s001-ppo-d-snp-h2001-047",
    "name": "UHC Dual Complete UT-S001 (PPO D-SNP)",
    "carrier": "UnitedHealthcare",
    "plan_type": "Medicare Advantage PPO",
    "cms_plan_type": "Local PPO",
    "contract_id": "H2001",
    "plan_id": "47",
    "snp": true,
    "premium": 37.6,
    "part_c_premium": 0.0,
    "part_d_premium": 54.7,
    "moop": 13900.0,
    "part_d_deductible": 615.0,
    "primary_care_copay": "$0 copay",
    "specialist_copay": "$0 copay",
    "er_copay": "$0 copay",
    "urgent_care_copay": "$0 copay",
    "telehealth_copay": "",
    "dme_coinsurance": "0% coinsurance",
    "dental_annual_max": 2000.0,
    "hearing_aid_allowance": 1500.0,
    "fitness_program": "",
    "transportation_trips": "Not covered",
    "otc_frequency": "",
    "offers_part_d": true,
    "overall_stars": 5,
    "part_c_stars": 4,
    "part_d_stars": 5,
    "summary_of_benefits_url": "https://s3.amazonaws.com/webflow-prod-assets/698622c974c0ac921982c3e3/69a3a19148e4ba8cfbcccad8_Summary-of-Benefits.pdf",
    "evidence_of_coverage_url": "https://s3.amazonaws.com/webflow-prod-assets/698622c974c0ac921982c3e3/69a3a19205866d678ee6da2a_Evidence-of-Coverage.pdf",
    "counties": [],
    "logo_url": "https://papiofficial.github.io/rsa/logos/unitedhealthcare.png"
  },
  {
    "slug": "uhc-dual-complete-ut-s2-hmo-pos-d-snp-h4604-026",
    "name": "UHC Dual Complete UT-S2 (HMO-POS D-SNP)",
    "carrier": "UnitedHealthcare",
    "plan_type": "Medicare Advantage HMO-POS",
    "cms_plan_type": "HMO/HMOPOS",
    "contract_id": "H4604",
    "plan_id": "26",
    "snp": true,
    "premium": 37.6,
    "part_c_premium": 0.0,
    "part_d_premium": 54.7,
    "moop": 9250.0,
    "part_d_deductible": 615.0,
    "primary_care_copay": "$0 copay",
    "specialist_copay": "$0 copay",
    "er_copay": "$0 copay",
    "urgent_care_copay": "$0 copay",
    "telehealth_copay": "",
    "dme_coinsurance": "0% coinsurance",
    "dental_annual_max": 2500.0,
    "hearing_aid_allowance": 2200.0,
    "fitness_program": "",
    "transportation_trips": "Not covered",
    "otc_frequency": "",
    "offers_part_d": true,
    "overall_stars": 4,
    "part_c_stars": 4,
    "part_d_stars": 5,
    "summary_of_benefits_url": "https://s3.amazonaws.com/webflow-prod-assets/698622c974c0ac921982c3e3/69a3a1c0955fb25967e522ab_Summary-of-Benefits.pdf",
    "evidence_of_coverage_url": "https://s3.amazonaws.com/webflow-prod-assets/698622c974c0ac921982c3e3/69a3a1c15386c90d9a62549d_Evidence-of-Coverage.pdf",
    "counties": [],
    "logo_url": "https://papiofficial.github.io/rsa/logos/unitedhealthcare.png"
  },
  {
    "slug": "uhc-dual-complete-ut-v001-ppo-d-snp-h2001-048",
    "name": "UHC Dual Complete UT-V001 (PPO D-SNP)",
    "carrier": "UnitedHealthcare",
    "plan_type": "Medicare Advantage PPO",
    "cms_plan_type": "Local PPO",
    "contract_id": "H2001",
    "plan_id": "48",
    "snp": true,
    "premium": 17.4,
    "part_c_premium": 0.0,
    "part_d_premium": 54.7,
    "moop": 10100.0,
    "part_d_deductible": 615.0,
    "primary_care_copay": "$0 copay",
    "specialist_copay": "$55 copay",
    "er_copay": "$130 copay",
    "urgent_care_copay": "$50 copay",
    "telehealth_copay": "",
    "dme_coinsurance": "0% coinsurance",
    "dental_annual_max": null,
    "hearing_aid_allowance": 199.0,
    "fitness_program": "",
    "transportation_trips": "",
    "otc_frequency": "",
    "offers_part_d": true,
    "overall_stars": 5,
    "part_c_stars": 4,
    "part_d_stars": 5,
    "summary_of_benefits_url": "https://s3.amazonaws.com/webflow-prod-assets/698622c974c0ac921982c3e3/69a3a197cfd8e4e75ebb86b4_Summary-of-Benefits.pdf",
    "evidence_of_coverage_url": "https://s3.amazonaws.com/webflow-prod-assets/698622c974c0ac921982c3e3/69a3a19897eddc436cf762e0_Evidence-of-Coverage.pdf",
    "counties": [],
    "logo_url": "https://papiofficial.github.io/rsa/logos/unitedhealthcare.png"
  },
  {
    "slug": "uhc-nursing-home-plan-ut-f001-ppo-i-snp-h0710-051",
    "name": "UHC Nursing Home Plan UT-F001 (PPO I-SNP)",
    "carrier": "UnitedHealthcare",
    "plan_type": "Medicare Advantage PPO",
    "cms_plan_type": "Local PPO",
    "contract_id": "H0710",
    "plan_id": "51",
    "snp": true,
    "premium": 54.7,
    "part_c_premium": 0.0,
    "part_d_premium": 54.7,
    "moop": 1500.0,
    "part_d_deductible": 590.0,
    "primary_care_copay": "",
    "specialist_copay": "",
    "er_copay": "$115 copay",
    "urgent_care_copay": "$40 copay",
    "telehealth_copay": "",
    "dme_coinsurance": "0% coinsurance",
    "dental_annual_max": null,
    "hearing_aid_allowance": 2500.0,
    "fitness_program": "",
    "transportation_trips": "",
    "otc_frequency": "",
    "offers_part_d": true,
    "overall_stars": 5,
    "part_c_stars": 5,
    "part_d_stars": 5,
    "summary_of_benefits_url": "",
    "evidence_of_coverage_url": "",
    "counties": [],
    "logo_url": "https://papiofficial.github.io/rsa/logos/unitedhealthcare.png"
  }
];